name: CI/CD Pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install required packages
        run: make install

      - name: Format code
        run: make format